### PR TITLE
Refactor decoration view

### PR DESCRIPTION
**Pull request by dennismajor1**
Did rake clean --all and rake to test this refactor of DecorationView against existing VC's

### CODE REVIEW

**Comment by dennismajor1** [comment]
Hi Will - I think the warning here is related to Ruby version that I'm using locally - wonder if we need to institute a .ruby-gemset and .ruby-version within the app? 

I pulled down the most recent master and did a merge of my feature branch onto the master (locally) and it merge and then ran all VCs OK.

I'm guessing as to the "merge with caution note" - but my guess is something to do with Ruby versions being used locally??

**Comment by willrax** [comment]
That was weird. The specs all passed fine on my computer as well. We'll see how the next build runs. I went ahead and just merged this pull request locally and pushed it up to master.

**Comment by willrax** [comment]
After I merged it started failing. There must be something funny going on with the specs. It was adding 4 subviews in the attachment view spec. I just reversed the test to say it shouldn't be 0.

**Comment by dennismajor1** [comment]
Does it rake clean --all; rake and then run OK for you? It does for me - I pulled the most current master before doing the refactor.

**Comment by willrax** [comment]
Pull down master and on the terminal do this:

``` bash
git checkout aca482be84af40c73a5981c29db62d1f772ae112
```

This should take you back to before my commit. If that passes, I'm not sure. haha

**Comment by dennismajor1** [comment]
OK - Thanks Will - will give it a go and see if I can figure out what's happening and correct - if not I'll do the git commit and go back.

**Comment by willrax** [comment]
It should be ok now. I made a commit to master to fix the spec. Are the latest changes working on your machine?

**Comment by dennismajor1** [comment]
I did a git fetch and git merge from master;  20 tests pass and when I compile and run all VC's work as expected ... :+1:

**Comment by willrax** [comment]
brilliant. :tada:

**Pull request merged**
