### PR TITLE
Post uikit-dynamics-catalog Custom Dynamic Item for code review

### PR DESCRIPTION
**Pull request by dennismajor1**
Hi Will,

This is not a request to merge but just a code review request (if you have the time) before I submit a RubyMotion bug report. If you are tight for time just say so - I'm fairly convinced that this is a RM bug but thought I'd get your thoughts before I submit.

If you do have the time could you please review CustomDynamicItemViewController especially def button_action(sender) and animator.addBehavior(attachment_behavior)

The animator, with the above addBehaviour method invokes the protocol method def bounds contained in PositionToBoundsMapping class

rake crashlog is showing something going sour at the point at which the protocol method bounds is accessed.

If you don't see any obvious screwup in my conversion of the code then I'll submit the bug report.

Thanks.

### CODE REVIEW

**Comment by willrax** [comment]
Hey Dennis,

Sorry been an extremely busy weekend. I'll take a look. :)

**Comment by dennismajor1** [comment]
NP Will - I thought you might be extra busy. Since I'm at a full stop until my ticket gets reviewed (I submitted it), I was wondering if you want me to complete one of the features you have taken on for yourself. 

If your quite busy, I don't mind doing another one. Barring that, I'll go back and start fleshing out some of the tests for each of the features.

**Comment by willrax** [comment]
I'm almost done with one of them so it should be ok. Thanks though :)

**Comment by dennismajor1** [comment]
ok :-)

On Sunday, 23 March 2014, Will Raxworthy notifications@github.com wrote:

> I'm almost done with one of them so it should be ok. Thanks though :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RubyCommotion/uikit-dynamics-catalog/pull/19#issuecomment-38396529
> .

## 

Sent from Gmail Mobile

**Comment by willrax** [comment]
This one is a weird one. I've tracked it to this point

``` ruby
centre_pt = button_bounds_dynamic_item.center
attachment_behavior = UIAttachmentBehavior.alloc.initWithItem(button_bounds_dynamic_item, attachedToAnchor:centre_pt)
attachment_behavior.setFrequency(2.0)
attachment_behavior.setDamping(0.3)
animator.addBehavior(attachment_behavior)
```

Still trying to figure out why.

**Comment by dennismajor1** [comment]
ASAICT animator.addBehavior(attachment_behavior) is calling the bounds protocol method and at that point I believe if you look at the line number in the crashlog it appears that as soon as bounds is invoked RM crashes - I forget its compaint.

**Comment by dennismajor1** [comment]
AFAICT :-)

**Comment by dennismajor1** [comment]
OK - closing this out for now - will re-submit a pull request for Custom Dynamic after I hear back from RM Support re the bug report related to this uikit-dynamics-catalog item.

**Comment by willrax** [comment]
Cool. I spent about an hour on the train home yesterday trying to nut it out. I didn't get a chance to compare it to the xcode project to see if it was a bug or a strange code example by Apple.

**Comment by dennismajor1** [comment]
I tried it as objective-c (Xcode) before i submitted bug report - it works fine as obj-c code.

**Comment by willrax** [comment]
There must be some sort of way we've implemented it that isn't carrying across to RubyMotion in the same way. Just before the crash it prints out null. I'm guessing this is related somehow.

**Comment by willrax** [comment]
I think this is actually something to do with an object being referenced after it's been released. It must be one of the instance variables needed by the animator.

In the crash report I get "EXC_BAD_ACCESS". Tonight I will try to track it down in debug mode.

**Comment by dennismajor1** [comment]
Ah good thought Will! - Thanks for taking the time on this one.

**Comment by willrax** [comment]
Here we go:

``` ruby
class PositionToBoundsMapping < NSObject
  attr_accessor :target

  def initWithTarget(target)
    self.init
    self.target = target
    self
  end

  def bounds
    target.bounds
  end

  def center
    CGPointMake(bounds.size.width, bounds.size.height)
  end

  def setCenter(value)
    target.bounds = CGRectMake(0, 0, value.x, value.y)
  end

  def transform
    target.transform
  end

  def setTransform(value)
    target.transform = value
  end
end
```

I changed around some of the attribute setting and that seemed to have fixed the first issue. Then I needed to change the setters to override the actual Obj-c ones.

**Comment by willrax** [comment]
Happy to make these changes a merge this pull request if you like.

**Comment by dennismajor1** [comment]
Thank you for figuring it out Will - yes please go ahead an merge.

**Comment by dennismajor1** [comment]
Hi Will ,

I tried to isolate and understand where my thinking went wrong so step by step I isolated the changes that needed to be made to my source code to get it to work:
- init or self.init - either of these work - not an issue
- Even tho RM documentation states that def transform=(transform) gets converted to def setTransform(transform) it's certainly not the case here since def transform=(transform) and  def center=(center) cause a crash.

OK so I can buy that RM doesn't do the conversion and it would have made more sense to use the setTransform and setCenter format.
- The one thing I don't understand is how you knew, or determined, that the :bounds attr_accessor had to be removed given that the Obj-C source code header file has a read/write bounds property?

Just trying to understand your thinking process :-)

**Comment by willrax** [comment]
Hey. It seemed to me that it was really just duplicate code. I'd have to have a look at the Xcode project again.

`attr_accessor` should write the getters, and setters for us but then we were writing the getter and the setter wasn't really needed because it was calling off the target. You could change it to:

``` ruby
class PositionToBoundsMapping < NSObject
  attr_accessor :target, :bounds

  def initWithTarget(target)
    self.init
    self.target = target
    self.bounds = target.bounds
    self
  end
```

then remove the bounds method and get the same thing. No real rhyme or reason to doing it the way I did, that's just how it ended up when it was working. :p

**Comment by dennismajor1** [comment]
Hi Will,

You would think that the code:

```
class PositionToBoundsMapping < NSObject
  attr_accessor :target, :bounds

  def initWithTarget(target)
    self.init
    self.target = target
    self.bounds = target.bounds
    self
  end
```

would compile and work but it crashes. I reset the simulator and did rake clean --all to be sure.

What I tried and did work and **somewhat** lines up with original Obj-C source (somewhat because they don't implement setBounds even tho' header property read/write option seems to call for it ) was this:

```
class PositionToBoundsMapping < NSObject

  attr_accessor :target

  def initWithTarget(target)
    init
    self.target = target
    self
  end

  def bounds
    # Pass through
    target.bounds
  end

  def setBounds
    true
  end
```

So I'm of the opinion that RB still has a bit of a bug in this sense:

Obj-C implements setBounds automatically (I think that's true for iOS 7) and therefore you don't see it written explicitly in the Obj-C source code. 

RM should do the same thing for `attr_accessor :target, :bounds`  but I don't think it does as you have to  delete `self.bounds = target.bounds`  and explicitly write the `def setBounds` to avoid a crash.

Anyhow, bottom line I'm learning a lot helping with this conversion - glad I was able to participate.

**Comment by dennismajor1** [comment]
Hi Will - looks like my suspicion that there is a RM bug involved might be the case - we'll see what is found. Here's is issue progress report link:

http://hipbyte.myjetbrains.com/youtrack/issue/RM-453

**Comment by willrax** [comment]
Ah cool. Nice find!

**Comment by dennismajor1** [comment]
Final feedback from RM Support - looks like it's an issue with RM for which there is no fix - they will include warning in next release of RM - see below:

Indeed the problem is the use of `attar_accessor`. The problem is a little hard to explain, but basically when you use `attr_accessor` you don’t define the method until runtime, in contrast to using `def`. Because this skips static compilation, we no longer have access to the metadata required to inflect if a method is a protocol method with specific parameter/return type requirements. Long story short, using `attr_accessor` in this case leads to the method wanting to return an object instead of a struct (CGRect) which crashes `objc_msgSend_stret`.

To fix it you should indeed use `def` to define the methods and as expected by the objc runtime you should use the `setBounds:` form.

We are going to print a warning in situations like these in the next release. Thanks for the feedback!

**Comment by dennismajor1** [comment]
Will - did you want me to close this pull request, make the changes to get Custom Dynamic Item working based on what needs be changed and then submit another pull request?

**Comment by willrax** [comment]
I think you can just update this pull request then we can merge this one in.

**Comment by dennismajor1** [comment]
Ok sounds good - will do.

On Thursday, 27 March 2014, Will Raxworthy notifications@github.com wrote:

> I think you can just update this pull request then we can merge this one
> in.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RubyCommotion/uikit-dynamics-catalog/pull/19#issuecomment-38881037
> .

## 

Sent from Gmail Mobile

**Pull request merged**
